const SYNC_ENDPOINT = 'https://script.google.com/macros/s/AKfycbxboZ_pGS10uW5wS-Thry6NrWljmGV1lCFPqGqW71ksyrMqmr_rAxWf89_Tb7mfAP0l/exec';
const workshopEvents = [
  ['yoga-0904','伸展瑜伽','2026-09-04','10:00','11:00'],['yoga-0905','伸展瑜伽','2026-09-05','10:00','11:00'],['sound-0905','音缽冥想｜夜間好眠','2026-09-05','19:30','20:30'],['sound-0906','音缽冥想｜循環提升','2026-09-06','10:30','11:30'],['yoga-0911','伸展瑜伽','2026-09-11','10:00','11:00'],['yoga-0912','伸展瑜伽','2026-09-12','10:00','11:00'],['yoga-0918','伸展瑜伽','2026-09-18','10:00','11:00'],['yoga-0920','伸展瑜伽','2026-09-20','10:00','11:00'],['bar-0927','微醺 Bar 派對','2026-09-27','14:00','16:00'],
  ...['02','09','16','23','30'].map(d=>[`bowl-${d}`,'音缽冥想',`2026-09-${d}`,'10:00','11:00']),...['03','10','17','24'].map(d=>[`bowl-thu-${d}`,'音缽冥想',`2026-09-${d}`,'10:00','11:00']),...['03','10','17','24'].map(d=>[`nutrition-${d}`,'營養小學堂Ｘ奶昔派對',`2026-09-${d}`,'14:00','16:00'])
].map(([id,title,date,start,end])=>({id,title,date,start,end,capacity:10}));
const $=selector=>document.querySelector(selector); let session=null,noticeTimer=null;
function showMessage(id,message=''){ $(id).textContent=message; }
function showNotice(message){const notice=$('#bookingNotice');notice.textContent=message;notice.classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>notice.classList.remove('show'),4200);}
function isMoreThan24HoursAway(event){return new Date(`${event.date}T${event.start}:00+08:00`).getTime()-Date.now()>24*60*60*1000;}
function canUseEvent(member,event){return !member.charityType||(member.charityType==='sound'?/音缽/.test(event.title):/哈達|伸展瑜伽/.test(event.title));}
function eventCard(event,member,counts,myBookings){const booked=counts[event.id]||0,left=event.capacity-booked,already=myBookings.some(booking=>booking.eventId===event.id),tooSoon=!isMoreThan24HoursAway(event),disabled=already||tooSoon||left<1||member.remaining<1;const label=already?'已預約':tooSoon?'請洽店家預約':left>0?`剩 ${left} 位`:'已額滿';return `<button class="calendar-event ${already?'is-booked':''} ${disabled?'is-disabled':''}" data-event-id="${event.id}" ${disabled?'disabled':''}><span class="event-time">${event.start}</span><span class="event-title">${event.title}</span><small>${label}</small></button>`;}
function bookingEditor(booking,member,counts,myBookings){const current=workshopEvents.find(event=>event.id===booking.eventId),canChange=current&&isMoreThan24HoursAway(current);if(!current)return '';const choices=workshopEvents.filter(event=>{const usedElsewhere=myBookings.some(item=>item.id!==booking.id&&item.eventId===event.id),left=event.capacity-(counts[event.id]||0)+(event.id===booking.eventId?1:0);return event.id===booking.eventId||(canUseEvent(member,event)&&!usedElsewhere&&isMoreThan24HoursAway(event)&&left>0);}).sort((a,b)=>`${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`));return `<article class="my-booking"><div><strong>${current.title}</strong><small>${current.date} ${current.start}–${current.end}</small></div><div class="booking-change"><select data-booking-target="${booking.id}" data-current-event="${booking.eventId}" ${canChange?'':'disabled'}>${choices.map(event=>`<option value="${event.id}" ${event.id===booking.eventId?'selected':''}>${event.date.slice(5)} ${event.start}｜${event.title}</option>`).join('')}</select><button class="change-button" data-booking-update="${booking.id}" disabled>${canChange?'選擇新課程':'請洽店家修改'}</button></div></article>`;}
function renderPortal(data){const member=data.membership,counts=data.eventCounts||{},myBookings=data.myBookings||[];$('#memberGreeting').textContent=`${member.customer}，你好`;$('#ticketInfo').innerHTML=`<div><span>票券</span><strong>${member.name}</strong></div><div><span>剩餘次數</span><strong>${member.remaining}／${member.total} 次</strong></div><div class="expiry-info"><span>使用期限</span><strong>至 ${member.expiresAt||'請洽店家確認'}</strong></div>`;$('#myBookings').innerHTML=`${member.remaining>0?`<button id="startBooking" class="start-booking">我要預約新課程 <span>剩 ${member.remaining} 次可用</span></button>`:''}${myBookings.length?`<div class="my-bookings-heading"><div><p>我的已預約</p><h3>需要換課嗎？</h3></div><span>開課前 24 小時以上可自行更改</span></div><div class="my-booking-list">${myBookings.map(booking=>bookingEditor(booking,member,counts,myBookings)).join('')}</div>`:''}`;const eventsByDate=workshopEvents.filter(event=>canUseEvent(member,event)).reduce((map,event)=>{(map[event.date]??=[]).push(event);return map;},{}),firstDay=new Date('2026-09-01T12:00:00').getDay(),cells=[];for(let i=0;i<firstDay;i++)cells.push('<div class="calendar-day is-empty"></div>');for(let day=1;day<=30;day++){const date=`2026-09-${String(day).padStart(2,'0')}`,events=(eventsByDate[date]||[]).sort((a,b)=>a.start.localeCompare(b.start));cells.push(`<section class="calendar-day"><time datetime="${date}">${day}</time><div class="day-events">${events.map(event=>eventCard(event,member,counts,myBookings)).join('')}</div></section>`);}while(cells.length%7)cells.push('<div class="calendar-day is-empty"></div>');$('#eventCalendar').innerHTML=cells.join('');}
async function login(){const customer=$('#memberName').value.trim(),code=$('#memberCode').value.trim().toUpperCase();if(!customer||!code){showMessage('#loginMessage','請完整輸入姓名與預約碼。');return;}showMessage('#loginMessage','驗證中…');try{const response=await fetch(`${SYNC_ENDPOINT}?action=member&customer=${encodeURIComponent(customer)}&code=${encodeURIComponent(code)}`),data=await response.json();if(!data.ok)throw new Error(data.error||'找不到有效票券');session={customer,code};$('#bookingLogin').classList.add('hidden');$('#bookingPortal').classList.remove('hidden');renderPortal(data);showMessage('#loginMessage');}catch(error){showMessage('#loginMessage',error.message||'暫時無法驗證，請稍後再試。');}}
async function reserve(eventId){if(!session)return;const button=document.querySelector(`[data-event-id="${eventId}"]`),event=workshopEvents.find(item=>item.id===eventId);if(!button)return;button.disabled=true;showMessage('#portalMessage');showNotice('正在保留名額，請稍候…');try{const response=await fetch(SYNC_ENDPOINT,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'customer-booking',customer:session.customer,code:session.code,eventId})}),data=await response.json();if(!data.ok)throw new Error(data.error||'預約失敗');renderPortal(data);showNotice(`✓ 已預約 ${event?.title||'課程'}`);}catch(error){button.disabled=false;showMessage('#portalMessage',error.message||'暫時無法預約，請稍後再試。');showNotice('預約失敗，請再試一次');}}
async function updateBooking(bookingId){if(!session)return;const select=document.querySelector(`[data-booking-target="${bookingId}"]`),target=select?.value,button=document.querySelector(`[data-booking-update="${bookingId}"]`);if(!target||!button||target===select.dataset.currentEvent)return;button.disabled=true;button.textContent='處理中…';showMessage('#portalMessage');showNotice('正在更改課程，請稍候…');try{const response=await fetch(SYNC_ENDPOINT,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'customer-update-booking',customer:session.customer,code:session.code,bookingId,eventId:target})}),data=await response.json();if(!data.ok)throw new Error(data.error||'更改失敗');renderPortal(data);showNotice('✓ 課程已更改完成');}catch(error){button.disabled=false;button.textContent='更改課程';showMessage('#portalMessage',error.message||'暫時無法更改課程，請稍後再試。');showNotice('更改失敗，請再試一次');}}
$('#memberLogin').addEventListener('click',login);$('#memberCode').addEventListener('keydown',event=>{if(event.key==='Enter')login();});$('#memberLogout').addEventListener('click',()=>{session=null;$('#bookingPortal').classList.add('hidden');$('#bookingLogin').classList.remove('hidden');$('#memberCode').value='';showMessage('#portalMessage');});document.addEventListener('change',event=>{const select=event.target.closest('[data-booking-target]');if(!select)return;const button=document.querySelector(`[data-booking-update="${select.dataset.bookingTarget}"]`);if(!button)return;const ready=select.value!==select.dataset.currentEvent;button.disabled=!ready;button.textContent=ready?'更改課程':'選擇新課程';});document.addEventListener('click',event=>{const start=event.target.closest('#startBooking');if(start){$('#bookingCalendarHeading').scrollIntoView({behavior:'smooth',block:'start'});showNotice('請從日曆中選擇想預約的課程');return;}const change=event.target.closest('[data-booking-update]');if(change){updateBooking(change.dataset.bookingUpdate);return;}const button=event.target.closest('[data-event-id]');if(button)reserve(button.dataset.eventId);});
